### ISSUE TITLE
Failed to load plugin demo

### ISSUE THREAD

**Issue by sadiqna** [EddyVerbruggen/nativescript-directions#1]
Failed to find module native-directions relative to app/tns_modules .

**Comment by sadiqna** [comment]
just removed plugin and added  from npm .it works now

**Comment by noscorpion** [comment]
I had the same problem.

For me the following steps solved this:
1. `rm -rf platforms/ hooks/`
2. `tns plugin remove nativescript-directions`
3. `tns plugin add nativescript-directions`
4. `tns run android`
