### ISSUE TITLE
Error after installed web pack

### ISSUE THREAD

**Issue by dzfweb** [EddyVerbruggen/nativescript-directions#10]
I've installed[ web pack](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html) on my project and then i'm getting the following error.

**ERROR in ./modules/pack.address/pack.address.component.ts
Module not found: Error: Can't resolve 'nativescript-directions' in 'C:\dev\fm-transportes\src\FM.Transportes\app\modules\pack.address'
 @ ./modules/pack.address/pack.address.component.ts 13:17-51
 @ ./app.module.ts
 @ ./main.ts**

**pack.address.component.ts**
```
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { DatabaseService, Package, Pack, Order, Address, PackStatus, State } from '../shared';
let Directions = require("nativescript-directions").Directions;

@Component({
    moduleId: module.id,
    selector: 'pack-address',
    templateUrl: './pack.address.component.html',
    styleUrls: ['./pack.address.component.css'],
})
export class PackAddressComponent {
...
```

Is the nativescript-directions plugin compatible ?
I also opened an issue on the web pack page 
#https://github.com/NativeScript/nativescript-dev-webpack/issues/81

**Comment by EddyVerbruggen** [comment]
It should be, but I see this change has not been pushed to npm. Please retry with 1.0.5.
