### ISSUE TITLE
How do I add a stop or have multiple directions using this plugin?

### ISSUE THREAD

**Issue by sanketsw** [EddyVerbruggen/nativescript-directions#11]
I want to have directions between three locations.
Start Point -> my current location
First Stop -> Say, Some store
Second Stop -> Say, some restaurant address
Second stop -> The final destination

**Comment by umeshrs** [comment]
Hello @sanketsw, were you able to get the waypoints to work ?

**Comment by EddyVerbruggen** [comment]
On Android, this is possible if we extend the plugin (add a `+to:` param to the querystring).

However, Apple Maps is used on iOS which doesn't support this. See the rather limited [Map Links API](https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html).

Perhaps we can extend the plugin by allowing you to launch Google Maps on iOS, which does support waypoints.

**Comment by EddyVerbruggen** [comment]
Please update to 1.1.0 and enjoy the fact you can now pass an array to `to` (see the updated README).

**Comment by sanketsw** [comment]
Thanks very much. I will give this a go this sometime soon.
