### ISSUE TITLE
Issue while using in angular 6

### ISSUE THREAD

**Issue by monikagupta78** [EddyVerbruggen/nativescript-directions#22]
I am getting this error - while trying to add this module in angular 6 component.

Module not found: Error: Can't resolve 'nativescript-directions'

I did install the plugin in my app using :, also i can see this in my node modules folder.
tns plugin add nativescript-directions

**this is the exact error :**
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'nativescript-directions' in 'D:\projects\ng-maps\src\app'
ERROR in ./src/app/directions/directions.component.ts
Module not found: Error: Can't resolve 'nativescript-directions' in 'D:\projects\ng-maps\src\app\directions'

in app.module.ts i have imported like this 
import { Directions } from "nativescript-directions";

In IDE , It is not showing any errors.

Any inputs pls.

**Comment by EddyVerbruggen** [comment]
This Angular 6 app uses this plugin, check it out: https://github.com/EddyVerbruggen/nativescript-pluginshowcase

**Comment by EddyVerbruggen** [comment]
How can I, without your repo?

**Comment by monikagupta78** [comment]
I can upload my code in github, will share the link.

**Comment by monikagupta78** [comment]
I uploaded my code here.
https://github.com/monikagupta78/ng-maps

you need to do
npm install ,
may be plungin  install as well as i had to do.
tns plugin add nativescript-directions

after this when i do ng serve, getting that error.

Thanks
Monika
