### ISSUE TITLE
Question: How many addresses does the navigate function can handle?

### ISSUE THREAD

**Issue by AgustinV08** [EddyVerbruggen/nativescript-directions#34]
Hi, i was wondering how many addresses can the plugin handle, also, i was receiving error from Google Maps when adding the addresses with the address postal code, are there any suggestions for that?

**Comment by EddyVerbruggen** [comment]
Can you not simply try?

**Comment by AgustinV08** [comment]
What i mean is that i saw in the documentation of the Google Directions API is that the max waypoints that you can introduce are 25, just commenting about that.

Also, are there any plans for the optimize waypoints enhancement mentioned here #28?

**Comment by EddyVerbruggen** [comment]
I guess that’s the limit here as well then, but never tested it.

And I have no plans with this plugin, but always happy to merge a PR of course.
