### ISSUE TITLE
TS transpiling issue

### ISSUE THREAD

**Issue by bradmartin** [EddyVerbruggen/nativescript-directions#4]
https://github.com/EddyVerbruggen/nativescript-directions/blob/master/directions.android.ts#L66

The current shipped .js has a bug, `application_1` is not defined. I'll have a PR soon.

**Comment by EddyVerbruggen** [comment]
Oh really? Wow.. I think I have to monkeypatch other repo's as well then.

**Comment by bradmartin** [comment]
This could be something with tsconfig.json or the import itself. Not sure
to be honest but the current source doesn't have the app module require
statement so it always failed. Works great now though so might just want to
check the output after transpiling to see what happens to application
import.
