### ISSUE TITLE
How to set Google Maps as default app

### ISSUE THREAD

**Issue by lorcanfurey** [EddyVerbruggen/nativescript-directions#6]
Hi, I was able to include and run the plugin in the Android emulator (it works nicely by the way), but I noticed that upon calling Directions.navigate(), I was asked if I should open with: Maps or Browser

Is there any way to direct navigation to Maps only (and not show other app options?)

Not even sure if this can be controlled/set through the plugin alone

**Comment by EddyVerbruggen** [comment]
Thanks!

You could try adding this:

```js
intent.setClassName("com.google.android.apps.maps", "com.google.android.maps.MapsActivity");
```

just before [this line](https://github.com/EddyVerbruggen/nativescript-directions/blob/master/directions.android.ts#L66)

I would advise not using this though as folks may not have GMaps installed.. and you may run into issues like #2

**Comment by lorcanfurey** [comment]
Given the caveat, having the option to still push Maps only is welcome 👍  

Thanks!
